import { BaseAdvancedFormlyFieldProperties } from '../../../base';

export type FormlyAddressFieldProperties = BaseAdvancedFormlyFieldProperties;

export const STATE_OPTIONS = [
  { displayTextValue: 'Alabama', key: 'AL' },
  { displayTextValue: 'Alaska', key: 'AK' },
  { displayTextValue: 'American Samoa', key: 'AS' },
  { displayTextValue: 'Arizona', key: 'AZ' },
  { displayTextValue: 'Arkansas', key: 'AR' },
  { displayTextValue: 'California', key: 'CA' },
  { displayTextValue: 'Colorado', key: 'CO' },
  { displayTextValue: 'Connecticut', key: 'CT' },
  { displayTextValue: 'Delaware', key: 'DE' },
  { displayTextValue: 'District Of Columbia', key: 'DC' },
  { displayTextValue: 'Federated States Of Micronesia', key: 'FM' },
  { displayTextValue: 'Florida', key: 'FL' },
  { displayTextValue: 'Georgia', key: 'GA' },
  { displayTextValue: 'Guam', key: 'GU' },
  { displayTextValue: 'Hawaii', key: 'HI' },
  { displayTextValue: 'Idaho', key: 'ID' },
  { displayTextValue: 'Illinois', key: 'IL' },
  { displayTextValue: 'Indiana', key: 'IN' },
  { displayTextValue: 'Iowa', key: 'IA' },
  { displayTextValue: 'Kansas', key: 'KS' },
  { displayTextValue: 'Kentucky', key: 'KY' },
  { displayTextValue: 'Louisiana', key: 'LA' },
  { displayTextValue: 'Maine', key: 'ME' },
  { displayTextValue: 'Marshall Islands', key: 'MH' },
  { displayTextValue: 'Maryland', key: 'MD' },
  { displayTextValue: 'Massachusetts', key: 'MA' },
  { displayTextValue: 'Michigan', key: 'MI' },
  { displayTextValue: 'Minnesota', key: 'MN' },
  { displayTextValue: 'Mississippi', key: 'MS' },
  { displayTextValue: 'Missouri', key: 'MO' },
  { displayTextValue: 'Montana', key: 'MT' },
  { displayTextValue: 'Nebraska', key: 'NE' },
  { displayTextValue: 'Nevada', key: 'NV' },
  { displayTextValue: 'New Hampshire', key: 'NH' },
  { displayTextValue: 'New Jersey', key: 'NJ' },
  { displayTextValue: 'New Mexico', key: 'NM' },
  { displayTextValue: 'New York', key: 'NY' },
  { displayTextValue: 'North Carolina', key: 'NC' },
  { displayTextValue: 'North Dakota', key: 'ND' },
  { displayTextValue: 'Northern Mariana Islands', key: 'MP' },
  { displayTextValue: 'Ohio', key: 'OH' },
  { displayTextValue: 'Oklahoma', key: 'OK' },
  { displayTextValue: 'Oregon', key: 'OR' },
  { displayTextValue: 'Palau', key: 'PW' },
  { displayTextValue: 'Pennsylvania', key: 'PA' },
  { displayTextValue: 'Puerto Rico', key: 'PR' },
  { displayTextValue: 'Rhode Island', key: 'RI' },
  { displayTextValue: 'South Carolina', key: 'SC' },
  { displayTextValue: 'South Dakota', key: 'SD' },
  { displayTextValue: 'Tennessee', key: 'TN' },
  { displayTextValue: 'Texas', key: 'TX' },
  { displayTextValue: 'Utah', key: 'UT' },
  { displayTextValue: 'Vermont', key: 'VT' },
  { displayTextValue: 'Virgin Islands', key: 'VI' },
  { displayTextValue: 'Virginia', key: 'VA' },
  { displayTextValue: 'Washington', key: 'WA' },
  { displayTextValue: 'West Virginia', key: 'WV' },
  { displayTextValue: 'Wisconsin', key: 'WI' },
  { displayTextValue: 'Wyoming', key: 'WY' },
];

export const COUNTRY_OPTIONS = [
  { displayTextValue: 'United States', key: 'US' },
  { displayTextValue: 'Canada', key: 'CA' },
  { displayTextValue: 'Mexico', key: 'MX' },
];
