apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace | default "devstream" }}
data:
  environment.js: |
    (function (window) {
      window.environment = window.environment || {{ .Values.environmentJSON | toPrettyJson | nindent 6 }};
    })(this);
